### ISSUE TITLE
[Feature] Implementacion de endpoints GETs

### ISSUE THREAD

**Issue by julitaras** [algoritmos-iii/algo3_backend#14]
## 🚀 Feature

- Un GET que me de el listado de alumnos. Posible endpoint (`/students`)
- Un GET que me de el listado de grupos (`/groups`)
- Un GET que me de las notas de un alumno (`/students/<padron>/grades`)
- Un GET con info de un alumno (`/students/<padron>`)
....

## Motivación

Justamente, el objetivo principal de esta app. Abastecer las necesidades del futuro front. Incluso la app de notas.
Probablemente mas a futuro se requieran algunos mas. A priori estoy craneando un front en react y diseñanando/explorando una nueva solucion

**Comment by ilitteri** [comment]
Estaría bueno armar un Issue por cada endpoint así los PRs en donde se trabajen pueden cerrar el Issue específico, poder distribuir mejor las tareas y además para podemos mantener las discusiones sobre cada uno por separado.

**Comment by ilitteri** [comment]
Pero aprovecho el Issue para explicarme mejor respecto al objetivo del backend ya que puedo ver el por qué de la confusión en la motivación del issue. 

La idea de este backend es servir a TODAS las aplicaciones que tengamos en la cátedra. Eso incluye al bot también además de la app de notas y futuras y por eso el MVP tiene la funcionalidad que tiene. 

Si aún no logro explicarme bien veo de buscar otra forma.

**Comment by julitaras** [comment]
> Pero aprovecho el Issue para explicarme mejor respecto al objetivo del backend ya que puedo ver el por qué de la confusión en la motivación del issue.
> 
> La idea de este backend es servir a TODAS las aplicaciones que tengamos en la cátedra. Eso incluye al bot también además de la app de notas y futuras y por eso el MVP tiene la funcionalidad que tiene.
> 
> Si aún no logro explicarme bien veo de buscar otra forma.

Claro que si Ivo. Lo que a mi me genera confusión es que se maneje la cola del bot en esta aplicación, cuando eso no pareciera ser responsabilidad de esta aplicación. ‘O se si me explico

**Comment by ilitteri** [comment]
Queda superpuesto por #15 #16 #17 #18
